// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc333.subsystems;

import org.usfirst.frc333.RobotMap;
import org.usfirst.frc333.commands.*;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import org.usfirst.frc330.wpilibj.BBDoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Chassis extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController leftDrive1 = RobotMap.chassisLeftDrive1;
    private final SpeedController leftDrive2 = RobotMap.chassisLeftDrive2;
    private final SpeedController leftDrive3 = RobotMap.chassisLeftDrive3;
    private final SpeedController rightDrive1 = RobotMap.chassisRightDrive1;
    private final SpeedController rightDrive2 = RobotMap.chassisRightDrive2;
    private final SpeedController rightDrive3 = RobotMap.chassisRightDrive3;
    private final Compressor compressor = RobotMap.chassisCompressor;
    private final Encoder quadratureEncoderL = RobotMap.chassisQuadratureEncoderL;
    private final Encoder quadratureEncoderR = RobotMap.chassisQuadratureEncoderR;
    private final BBDoubleSolenoid shifter = RobotMap.chassisShifter;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new TankDrive());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
}

