// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc330.commands.drivecommands;
import org.usfirst.frc330.constants.ChassisConst;
import org.usfirst.frc330.wpilibj.PIDGains;

import edu.wpi.first.wpilibj.command.BBCommandGroup;

/**
 *
 */
public class  DriveDistanceAtRelAngle extends BBCommandGroup{
    
    public DriveDistanceAtRelAngle(double distance, double angle, PIDGains driveGains, PIDGains gyroDriveGains, PIDGains gyroTurnGains)
    {
    	addSequential(new TurnGyroRel(angle, 5,gyroTurnGains));
        addSequential(new DriveDistanceAtRelAngle_NoTurn(distance, 6, angle, 5, true, driveGains, gyroDriveGains));
    }
    
    public DriveDistanceAtRelAngle(double distance, double distanceTolerance, double angle, double timeout, boolean stopAtEnd, PIDGains driveGains, PIDGains gyroDriveGains, PIDGains gyroTurnGains)
    {
        addSequential(new TurnGyroRel(angle,5,1.0,false,gyroTurnGains));
        addSequential(new DriveDistanceAtRelAngle_NoTurn(distance, distanceTolerance, angle, timeout, stopAtEnd, driveGains, gyroDriveGains));
    }
    
}
