// RobotBuilder Version: 2.0BB
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc330.subsystems;

import org.usfirst.frc330.RobotMap;
import org.usfirst.frc330.commands.*;
import org.usfirst.frc330.constants.PickupConst;

import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Solenoid;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import org.usfirst.frc330.wpilibj.BBDoubleSolenoid;
import org.usfirst.frc330.wpilibj.BBSolenoid;
import org.usfirst.frc330.wpilibj.DualSpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Pickup extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final BBSolenoid wings = RobotMap.pickupWings;
    private final SpeedController pickup1 = RobotMap.pickupPickup1;
    private final SpeedController pickup2 = RobotMap.pickupPickup2;
    private final DualSpeedController pickup = RobotMap.pickupPickup;
    private final BBSolenoid pincher = RobotMap.pickupPincher;
    private final BBSolenoid lift = RobotMap.pickupLift;
    private final DigitalInput gearSensor = RobotMap.pickupGearSensor;
    private final SpeedController hopper = RobotMap.pickupHopper;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void pickupOff() {
    	pickup.set(0.0);
    }
    
    public void pickupOn() {
    	pickup.set(PickupConst.PICKUP_SPEED);
    }
    
    public void pickupOn(double speed) {
    	pickup.set(speed);
    }
    
    public void pickupReverse() {
    	pickup.set(PickupConst.PICKUP_REVERSE_SPEED);
    }
    
    public void wingsOpen() {
    	wings.set(true);
    }
    
    public void wingsClosed() {
    	wings.set(false);
    }
    
    public void gearPickupDown() {
    	lift.set(true);
    }
    
    public void gearPickupUp() {
    	lift.set(false);
    }
    
    public void hopperAgitate() {
    	hopper.set(PickupConst.HOPPER_AGITATE_SPEED);
    }
    
	public void hopperAgitateWhileShooting() {
		hopper.set(PickupConst.HOPPER_AGITATE_SHOOT_SPEED);
	}
    
    public void hopperFeed() {
    	hopper.set(PickupConst.HOPPER_FEED_SPEED);
    }
    
    public void hopperStop(){
    	hopper.stopMotor();
    }

	public void gearGrab() {
		pincher.set(true);
	}

	public void gearRelease() {
		pincher.set(false);
	}

	public boolean isGearPresent() {
		return  !gearSensor.get();
		
	}
	
	
}

